nome_carro = input("Digite o nome do carro: ")
valor_carro = float(input("Digite o valor do carro"))
consumo_por_litro = float(input("Digite o consumo por litro: "))
print("---------------------------------------------")
print("| Carro:", nome_carro)
print("| Valor:", valor_carro)
print("| consumo por litro:", consumo_por_litro)
print("----------------------------------------------")
